### ISSUE TITLE
Supervisord is running as root and it is searching...

### ISSUE THREAD

**Issue by milliorn** [Urothis/nwnxee-template#16]
UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.

This is the first link Google returns on this message
https://github.com/Supervisor/supervisor/issues/741

Your going to have to look at the picture.  It's the second line down from the top.  
/usr/lib/python2.7/ etc etc.

![image](https://user-images.githubusercontent.com/39207179/43029748-b4d7a5f4-8c4e-11e8-88ac-c9e6b9feca9b.png)

**Comment by urothis** [comment]
Issue is relative to Grafana image. I don't think we can correct this issue without rolling our own Grafana image.
