### ISSUE TITLE
nwserverLog1.txt & nwserverError1.txt

### ISSUE THREAD

**Issue by milliorn** [Urothis/nwnxee-template#17]
**nwserverLog1.txt & nwserverError1.txt** text files do not overwrite or rotate.  The log is made after the first launch with docker-compose up.  After the server resets with the nwnxee command and starts a new server it does not write a new log file or overwrite the log file.

Assuming this is a missing feature that needs to be added.  Rotating logs from 0-9 is desirable.  If not at least an overwrite.  A switch between the two possibilities would be optimal.

**Comment by urothis** [comment]
Not possible on our end.
